//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFight.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.googleapis.com")]
        public string GoogleURLBase {
            get {
                return ((string)(this["GoogleURLBase"]));
            }
            set {
                this["GoogleURLBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3fc5829e68c9c8702")]
        public string GoogleCxCode {
            get {
                return ((string)(this["GoogleCxCode"]));
            }
            set {
                this["GoogleCxCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyB5meOmbnFNUMehzGUA5BJGVBywVEaaWQo")]
        public string GoogleApiKey {
            get {
                return ((string)(this["GoogleApiKey"]));
            }
            set {
                this["GoogleApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.cognitive.microsoft.com")]
        public string BingURLBase {
            get {
                return ((string)(this["BingURLBase"]));
            }
            set {
                this["BingURLBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62aa0b34-bedf-49dc-971b-5a54f10f685d")]
        public string BingCustomConfiguration {
            get {
                return ((string)(this["BingCustomConfiguration"]));
            }
            set {
                this["BingCustomConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a04ce50dfc4240e3aee4c3fd713d5738")]
        public string BingAccessKey {
            get {
                return ((string)(this["BingAccessKey"]));
            }
            set {
                this["BingAccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/customsearch/v1")]
        public string GoogleServicePath {
            get {
                return ((string)(this["GoogleServicePath"]));
            }
            set {
                this["GoogleServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/bingcustomsearch/v7.0/search")]
        public string BingServicePath {
            get {
                return ((string)(this["BingServicePath"]));
            }
            set {
                this["BingServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ocp-Apim-Subscription-Key")]
        public string BingServiceHeader {
            get {
                return ((string)(this["BingServiceHeader"]));
            }
            set {
                this["BingServiceHeader"] = value;
            }
        }
    }
}
